VULNERABLE_PATTERNS = {
    "RSA": {
        "patterns": [
            r"RSA\.generate\(",
            r"rsa\.generate_private_key\(",
            r"createSign\(['\"]RSA",
            r"crypto\.createSign\(",
            r"new\s+RSAKey\(",
            r"RSA-\d{4}",
            r"generate_rsa\(",
            r"RSAPrivateKey",
            r"RSAPublicKey",
            r"PKCS1_v1_5",
        ],
        "severity": "CRITICAL",
        "quantum_vulnerable": True,
        "nist_replacement": "CRYSTALS-Dilithium (ML-DSA, FIPS 204)",
        "library": "pqcrypto or liboqs",
        "timeline": "Vulnerable to attack by 2030-2033",
        "why": "Shor's algorithm breaks RSA in polynomial time on a quantum computer.",
    },
    "ECC": {
        "patterns": [
            r"ec\.generate_private_key\(",
            r"SECP256K1",
            r"SECP256R1",
            r"secp256k1",
            r"P-256",
            r"prime256v1",
            r"createECDH\(",
            r"ellipticCurve",
            r"EC_KEY_new",
            r"brainpoolP",
        ],
        "severity": "CRITICAL",
        "quantum_vulnerable": True,
        "nist_replacement": "CRYSTALS-Kyber (ML-KEM, FIPS 203) for key exchange",
        "library": "pqcrypto or liboqs",
        "timeline": "Vulnerable to attack by 2028-2033",
        "why": "Shor's algorithm solves the elliptic curve discrete log problem efficiently.",
    },
    "SHA1": {
        "patterns": [
            r"hashlib\.sha1\(",
            r"SHA1\(",
            r"createHash\(['\"]sha1",
            r"DigestUtils\.sha1",
            r"MessageDigest\.getInstance\(['\"]SHA-1",
            r"sha1sum",
            r"SHA_1",
        ],
        "severity": "HIGH",
        "quantum_vulnerable": True,
        "nist_replacement": "SHA-384 or SHA-512",
        "library": "hashlib (built-in)",
        "timeline": "Already weak classically, worse with quantum",
        "why": "Grover's algorithm halves the effective security of SHA-1 from 80 bits to ~40 bits.",
    },
    "AES128": {
        "patterns": [
            r"AES-128",
            r"aes-128",
            r"AES\.new\(.*128",
            r"AES_128",
            r"aes_128",
            r"KeySize\.Bits128",
            r"128.*AES",
        ],
        "severity": "MEDIUM",
        "quantum_vulnerable": True,
        "nist_replacement": "AES-256",
        "library": "pycryptodome (built-in AES-256)",
        "timeline": "Weakened but not broken by quantum",
        "why": "Grover's algorithm reduces AES-128 effective key strength to 64 bits — below safe threshold.",
    },
    "MD5": {
        "patterns": [
            r"hashlib\.md5\(",
            r"MD5\(",
            r"createHash\(['\"]md5",
            r"DigestUtils\.md5",
            r"MessageDigest\.getInstance\(['\"]MD5",
            r"md5sum",
            r"MD5_Init",
        ],
        "severity": "HIGH",
        "quantum_vulnerable": True,
        "nist_replacement": "SHA-256 minimum, SHA-384 preferred",
        "library": "hashlib (built-in)",
        "timeline": "Already broken classically",
        "why": "MD5 is classically broken; Grover's makes brute-force even faster on quantum hardware.",
    },
    "DIFFIE_HELLMAN": {
        "patterns": [
            r"dh\.generate_parameters\(",
            r"DHE",
            r"createDiffieHellman\(",
            r"DH_generate_parameters",
            r"DHParameterSpec",
            r"KeyAgreement\.getInstance\(['\"]DH",
        ],
        "severity": "CRITICAL",
        "quantum_vulnerable": True,
        "nist_replacement": "CRYSTALS-Kyber (ML-KEM, FIPS 203)",
        "library": "pqcrypto or liboqs",
        "timeline": "Vulnerable to Shor's algorithm",
        "why": "Shor's algorithm solves the discrete logarithm problem underlying Diffie-Hellman.",
    },
    "DSA": {
        "patterns": [
            r"DSA\.generate\(",
            r"dsa\.generate_private_key\(",
            r"DSAPrivateKey",
            r"KeyPairGenerator\.getInstance\(['\"]DSA",
            r"createSign\(['\"]DSA",
        ],
        "severity": "CRITICAL",
        "quantum_vulnerable": True,
        "nist_replacement": "CRYSTALS-Dilithium (ML-DSA, FIPS 204) or SPHINCS+",
        "library": "pqcrypto or liboqs",
        "timeline": "Vulnerable to Shor's algorithm by 2030",
        "why": "DSA relies on discrete logarithm hardness, which Shor's algorithm breaks.",
    },
}

SKIP_DIRS = {".git", "node_modules", "__pycache__", ".tox", ".venv", "venv", "env", "dist", "build", ".mypy_cache"}

LANGUAGE_EXTENSIONS = {
    ".py": "Python",
    ".js": "JavaScript",
    ".ts": "TypeScript",
    ".tsx": "TypeScript",
    ".jsx": "JavaScript",
    ".go": "Go",
    ".rs": "Rust",
    ".java": "Java",
    ".c": "C",
    ".cpp": "C++",
    ".cc": "C++",
    ".cs": "C#",
    ".rb": "Ruby",
    ".php": "PHP",
    ".swift": "Swift",
    ".kt": "Kotlin",
}
