import json
from datetime import datetime
from pathlib import Path

from rich.console import Console
from rich.table import Table
from rich.text import Text
from rich import box

from .scanner import Finding
from .analyzer import Analysis

console = Console()

SEVERITY_COLORS = {
    "CRITICAL": "bold red",
    "HIGH": "bold yellow",
    "MEDIUM": "yellow",
    "LOW": "green",
}

SEVERITY_EMOJI = {
    "CRITICAL": "[red]CRITICAL[/red]",
    "HIGH": "[yellow]HIGH[/yellow]",
    "MEDIUM": "[yellow]MEDIUM[/yellow]",
    "LOW": "[green]LOW[/green]",
}


def _severity_order(s: str) -> int:
    return {"CRITICAL": 0, "HIGH": 1, "MEDIUM": 2, "LOW": 3}.get(s, 9)


def print_rich_table(findings: list[Finding], analyses: list[Analysis] | None = None) -> None:
    if not findings:
        console.print("\n[bold green]No quantum-vulnerable cryptography found![/bold green]\n")
        return

    sorted_findings = sorted(findings, key=lambda f: _severity_order(f.severity))

    table = Table(
        title=f"\n[bold]QuantumMigrate Scan Results — {len(findings)} finding(s)[/bold]",
        box=box.ROUNDED,
        show_lines=True,
        highlight=True,
    )
    table.add_column("Severity", style="bold", width=10)
    table.add_column("Type", style="cyan", width=18)
    table.add_column("File", style="white", width=40)
    table.add_column("Line", justify="right", width=6)
    table.add_column("NIST Replacement", style="green", width=35)

    for f in sorted_findings:
        color = SEVERITY_COLORS.get(f.severity, "white")
        table.add_row(
            Text(f.severity, style=color),
            f.vuln_type,
            Path(f.file).name,
            str(f.line_number),
            f.nist_replacement,
        )

    console.print(table)

    if analyses:
        console.print("\n[bold]AI Analysis (top findings):[/bold]\n")
        for a in analyses[:5]:
            sev = SEVERITY_EMOJI.get(a.finding.severity, a.finding.severity)
            console.print(f"[bold]{sev} — {a.finding.vuln_type}[/bold] in [cyan]{Path(a.finding.file).name}:{a.finding.line_number}[/cyan]")
            console.print(f"  [dim]{a.explanation}[/dim]")
            if a.replacement_code:
                console.print(f"  [green]Replacement:[/green]\n  [white]{a.replacement_code}[/white]")
            console.print()

    counts = {}
    for f in findings:
        counts[f.severity] = counts.get(f.severity, 0) + 1
    console.print("[bold]Summary:[/bold]")
    for sev in ["CRITICAL", "HIGH", "MEDIUM", "LOW"]:
        if sev in counts:
            color = SEVERITY_COLORS[sev]
            console.print(f"  [{color}]{sev}[/{color}]: {counts[sev]}")
    console.print()


def write_json(findings: list[Finding], analyses: list[Analysis] | None, output_path: str = "quantum_report.json") -> None:
    analysis_map = {(a.finding.file, a.finding.line_number): a for a in (analyses or [])}

    data = {
        "scan_date": datetime.utcnow().isoformat() + "Z",
        "total_findings": len(findings),
        "findings": [],
    }

    for f in findings:
        entry = {
            "file": f.file,
            "line_number": f.line_number,
            "line_content": f.line_content.strip(),
            "vuln_type": f.vuln_type,
            "severity": f.severity,
            "language": f.language,
            "nist_replacement": f.nist_replacement,
            "library": f.library,
            "timeline": f.timeline,
        }
        a = analysis_map.get((f.file, f.line_number))
        if a:
            entry["ai_explanation"] = a.explanation
            entry["replacement_code"] = a.replacement_code
            entry["urgency"] = a.urgency
        data["findings"].append(entry)

    Path(output_path).write_text(json.dumps(data, indent=2), encoding="utf-8")
    console.print(f"[green]JSON report written to {output_path}[/green]")


def write_markdown(findings: list[Finding], analyses: list[Analysis] | None, output_path: str = "QUANTUM_MIGRATION.md") -> None:
    analysis_map = {(a.finding.file, a.finding.line_number): a for a in (analyses or [])}
    sorted_findings = sorted(findings, key=lambda f: _severity_order(f.severity))

    lines = [
        "# Quantum Migration Report",
        "",
        f"> Generated by [QuantumMigrate](https://github.com/maddykws/QuantumMigrate) on {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}",
        "",
        "## Summary",
        "",
        f"**Total findings:** {len(findings)}",
        "",
        "| Severity | Count |",
        "|----------|-------|",
    ]

    counts: dict[str, int] = {}
    for f in findings:
        counts[f.severity] = counts.get(f.severity, 0) + 1
    for sev in ["CRITICAL", "HIGH", "MEDIUM", "LOW"]:
        if sev in counts:
            lines.append(f"| {sev} | {counts[sev]} |")

    lines += [
        "",
        "## Findings",
        "",
        "| Severity | Type | File | Line | NIST Replacement |",
        "|----------|------|------|------|-----------------|",
    ]

    for f in sorted_findings:
        fname = Path(f.file).name
        lines.append(f"| {f.severity} | {f.vuln_type} | `{fname}` | {f.line_number} | {f.nist_replacement} |")

    lines += ["", "## Detailed Analysis", ""]

    for f in sorted_findings:
        a = analysis_map.get((f.file, f.line_number))
        lines.append(f"### {f.vuln_type} — `{Path(f.file).name}:{f.line_number}`")
        lines.append("")
        lines.append(f"**Severity:** {f.severity}  ")
        lines.append(f"**Language:** {f.language}  ")
        lines.append(f"**Timeline:** {f.timeline}  ")
        lines.append("")
        lines.append("**Vulnerable code:**")
        lines.append(f"```{f.language.lower()}")
        lines.append(f.line_content.strip())
        lines.append("```")
        lines.append("")
        if a:
            lines.append(f"**Why it's vulnerable:** {a.explanation}")
            lines.append("")
            lines.append(f"**Replacement ({f.nist_replacement}):**")
            lines.append(f"```{f.language.lower()}")
            lines.append(a.replacement_code)
            lines.append("```")
        else:
            lines.append(f"**Why it's vulnerable:** {f.why}")
            lines.append("")
            lines.append(f"**Replace with:** {f.nist_replacement} via `{f.library}`")
        lines.append("")

    lines += [
        "## Resources",
        "",
        "- [NIST Post-Quantum Cryptography Standards](https://csrc.nist.gov/projects/post-quantum-cryptography)",
        "- [CRYSTALS-Kyber (ML-KEM, FIPS 203)](https://pq-crystals.org/kyber/)",
        "- [CRYSTALS-Dilithium (ML-DSA, FIPS 204)](https://pq-crystals.org/dilithium/)",
        "- [SPHINCS+ (SLH-DSA, FIPS 205)](https://sphincs.org/)",
        "- [CISA Post-Quantum Cryptography Initiative](https://www.cisa.gov/quantum)",
        "- [liboqs — Open Quantum Safe](https://openquantumsafe.org/)",
        "",
    ]

    Path(output_path).write_text("\n".join(lines), encoding="utf-8")
    console.print(f"[green]Markdown report written to {output_path}[/green]")
